# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI


#Trigger the workflow on any push to the main branch ir pull request

on:
    push:
        branches: 
            - main
    pull_request:
            - main

jobs:
    test:
        runs_on: ubuntu-latest

        steps:
            #Step 1 : check out the code from repo

            - name: Check out name
              uses: actions/checkout@v2

            #step 2 :Set up python enviroment

            - name: Set up python
              uses: actions/setup_python@v2
              with: 
                pyhton_vesrion:'3.8'

            # install depenedency

            - name: Install dependencies
              run:
                pyhton -m pip install --upgrade pip
                pip install -r requirements.txt
                
            #run tests

            - name: Run tests
              run: pytest
